### ISSUE TITLE
Can't install editdistance on Python 3.6.1 Windows10

### ISSUE THREAD

**Issue by dolaorz** [aflc/editdistance#13] opened 2017-04-17 05:04 UTC
PS C:\Users\silyn> pip install editdistance
Collecting editdistance
  Using cached editdistance-0.3.1.tar.gz
Installing collected packages: editdistance
  Running setup.py install for editdistance ... error
    Complete output from command c:\users\silyn\appdata\local\programs\python\python36\python.ex
e -u -c "import setuptools, tokenize;__file__='C:\\Users\\silyn\\AppData\\Local\\Temp\\pip-build
-2jn4cy88\\editdistance\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\si
lyn\AppData\Local\Temp\pip-cvfu8ci_-record\install-record.txt --single-version-externally-manage
d --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\editdistance
    copying editdistance\__init__.py -> build\lib.win-amd64-3.6\editdistance
    copying editdistance\_editdistance.h -> build\lib.win-amd64-3.6\editdistance
    copying editdistance\def.h -> build\lib.win-amd64-3.6\editdistance
    running build_ext
    building 'editdistance.bycython' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\editdistance
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /
W3 /GL /DNDEBUG /MD -I./editdistance -Ic:\users\silyn\appdata\local\programs\python\python36\inc
lude -Ic:\users\silyn\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\M
icrosoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\V
C\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Pro
gram Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\
10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\u
m" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /Tpeditdistance/_
editdistance.cpp /Fobuild\temp.win-amd64-3.6\Release\editdistance/_editdistance.obj
    _editdistance.cpp
    editdistance/_editdistance.cpp: warning C4819: The file contains a character that cannot be
represented in the current code page (936). Save the file in Unicode format to prevent data loss
    editdistance/_editdistance.cpp(117): error C2059: syntax error: 'if'
    editdistance/_editdistance.cpp(118): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(119): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(120): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(121): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(122): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(123): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(124): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(125): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(126): error C2059: syntax error: 'else'
    editdistance/_editdistance.cpp(127): error C2059: syntax error: 'return'
    editdistance/_editdistance.cpp(128): error C2059: syntax error: '}'
    editdistance/_editdistance.cpp(128): error C2143: syntax error: missing ';' before '}'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\c
l.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\silyn\appdata\local\programs\python\python36\python.exe -u -c "import setuptoo
ls, tokenize;__file__='C:\\Users\\silyn\\AppData\\Local\\Temp\\pip-build-2jn4cy88\\editdistance\
\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" install --record C:\Users\silyn\AppData\Local\Temp\p
ip-cvfu8ci_-record\install-record.txt --single-version-externally-managed --compile" failed with
 error code 1 in C:\Users\silyn\AppData\Local\Temp\pip-build-2jn4cy88\editdistance\

**Comment by aflc** [comment] 2017-11-05 00:31
Thanks to report the issue and sorry for late reply.
I released v0.4, and I tested on Windows 10, Python 3.6 with binary wheels.
So please retry this if you could.

**Comment by aflc** [comment] 2017-11-14 11:05
Closing this issue, but feel free to reopen if any problems.

**Closed by aflc** 2017-11-14 11:05 UTC

**Comment by karan-cmd** [comment] 2020-05-11 04:21
getting error with exit status 1
what to do ??

pip install editdistance
Collecting editdistance
  Downloading editdistance-0.5.3.tar.gz (27 kB)
Could not build wheels for editdistance, since package 'wheel' is not installed.
Installing collected packages: editdistance
    Running setup.py install for editdistance ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-_7bpzfp5\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-_7bpzfp5\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\punit\AppData\Local\Temp\pip-record-nxzz0aug\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\editdistance'
         cwd: C:\Users\punit\AppData\Local\Temp\pip-install-_7bpzfp5\editdistance\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\editdistance
    copying editdistance\__init__.py -> build\lib.win-amd64-3.8\editdistance
    copying editdistance\_editdistance.h -> build\lib.win-amd64-3.8\editdistance
    copying editdistance\def.h -> build\lib.win-amd64-3.8\editdistance
    running build_ext
    building 'editdistance.bycython' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-_7bpzfp5\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-_7bpzfp5\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\punit\AppData\Local\Temp\pip-record-nxzz0aug\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\editdistance' Check the logs for full command output.

C:\Users\punit>pip install wheel
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2

C:\Users\punit>pip install editdistance
Collecting editdistance
  Using cached editdistance-0.5.3.tar.gz (27 kB)
Building wheels for collected packages: editdistance
  Building wheel for editdistance (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\punit\AppData\Local\Temp\pip-wheel-mnf0q3hb'
       cwd: C:\Users\punit\AppData\Local\Temp\pip-install-uf_p48h0\editdistance\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\editdistance
  copying editdistance\__init__.py -> build\lib.win-amd64-3.8\editdistance
  copying editdistance\_editdistance.h -> build\lib.win-amd64-3.8\editdistance
  copying editdistance\def.h -> build\lib.win-amd64-3.8\editdistance
  running build_ext
  building 'editdistance.bycython' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for editdistance
  Running setup.py clean for editdistance
Failed to build editdistance
Installing collected packages: editdistance
    Running setup.py install for editdistance ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\punit\AppData\Local\Temp\pip-record-80dt_x5f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\editdistance'
         cwd: C:\Users\punit\AppData\Local\Temp\pip-install-uf_p48h0\editdistance\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\editdistance
    copying editdistance\__init__.py -> build\lib.win-amd64-3.8\editdistance
    copying editdistance\_editdistance.h -> build\lib.win-amd64-3.8\editdistance
    copying editdistance\def.h -> build\lib.win-amd64-3.8\editdistance
    running build_ext
    building 'editdistance.bycython' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\punit\\AppData\\Local\\Temp\\pip-install-uf_p48h0\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\punit\AppData\Local\Temp\pip-record-80dt_x5f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\editdistance' Check the logs for full command output.

**Comment by sapphire008** [comment] 2021-01-27 01:51
I have encountered the same issue. Windows 10, Python 3.8.5, with `pip install editdistance`

**Comment by juliandehne** [comment] 2021-08-06 13:41
I can reproduce the error on windows 10 with WSL 2:

pip install editdistance 

 creating build/temp.linux-x86_64-3.8/editdistance
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./editdistance -I/usr/include/python3.8 -c editdistance/_editdistance.cpp -o build/temp.linux-x86_64-3.8/editdistance/_editdistance.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for editdistance
